framework:
    secret: '%env(APP_SECRET)%'
    router:
        utf8: true
    validation:
        enable_attributes: true
    handle_all_throwables: true
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_httponly: true
        cookie_samesite: strict
        cookie_secure: auto
        cookie_lifetime: 3600
        gc_maxlifetime: 3600
