server {
    listen __PORT__;
    server_name _;
    root /app/public;
    index index.php;
    client_max_body_size 16k;
    add_header X-Content-Type-Options nosniff always;
    location / {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_pass 127.0.0.1:9000;
    }
}
