services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude: ['../src/Kernel.php', '../src/Entity/', '../src/Dto/', '../src/Exception/', '../src/Service/PaymentResult.php']
    App\Service\PaymentProcessorInterface: '@App\Service\FakePaymentProcessor'
